[package]
name = "tcp_chat_server"
version = "0.1.0"
authors = ["David Vega"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# enabling everything for tokio
tokio = { version = "1.0", features = ["full"] }
