[package]
name = "actix_service"
version = "0.1.0"
authors = ["David Vega Lichacz <davidvegalichacz@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
