version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: todos
      POSTGRES_USER: todos
      POSTGRES_DB: todos
    ports:
      - 5432:5432